name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: franchise_backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./franchise_backend/
          log-level : verbose
          exclude: |
            - .git
            - .github
            - .env
            - node_modules
            - package-lock.json
            - package.json
            - README.md
            - .gitignore

