const mongoose = require("mongoose");

const franchiseSchema = new mongoose.Schema({
  flsNumber: String,
  customSlug: String,
  brandName: String,
  brandLogo: String,
  brandBanner: String,
  aboutUs: String,
  category: String,
  subcategory: String,
  businessModel: String,
  keywords: String,
  entityName: String,
  website: String,
  foundedDate: Date,
  franchisingSince: Date,
  corporatePhone: String,
  corporateLocations: Number,
  franchiseLocations: Number,
  streetAddress: String,
  city: String,
  state: String,
  zipCode: String,
  investmentLow: Number,
  investmentHigh: Number,
  franchiseFee: Number,
  liquidCapital: Number,
  thirdPartyFinancing: String,
  royaltyFee: Number,
  marketingFee: Number,
  localAdType: String,
  localAdAmount: Number,
  localAdRequired: String,
  nationalAdType: String,
  nationalAdAmount: Number,
  nationalAdRequired: String,
  spaceLow: Number,
  spaceHigh: Number,
  ownerOperatorRequired: String,
  absenteeOwnershipAllowed: String,
  staffRequirements: String,
  operationalHours: String,
  trainingHours: Number,
  trainingLocation: String,
  trainingDescription: String,
  ongoingSupport: String,
  territoryProtection: String,
  internationalOpportunities: String,
  opportunityTypes: String,
  trademarkStatus: String,
  trademarkNumber: String,
  financialDisclosure: String,
  financialDetails: String,
  brokerReferrals: String,
  brokerCommission: Number,
  commissionType: String,
  minCommission: Number,
  maxCommission: Number,
  brokerProgramDetails: String,
  facebookUrl: String,
  instagramUrl: String,
  twitterUrl: String,
  linkedinUrl: String,
  youtubeUrl: String,
  brandVideoUrl: String,
  testimonialVideoUrl: String,
  pressMentions: String,
  galleryImages: [String],
  marketingBrochure: String,
  leadEmail: String,
  calendlyUrl: String,
  responseTime: String,
  fddFile: String,
  brandLogo: String,
  brandBanner: String,
  marketingBrochure: String,
  galleryImages: [String],

  createdAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model("FranchiseOpportunity", franchiseSchema);
